class Database {
  final specialities = [
    "G.P (General Practitioner)",
    "M.B.B.S",
    "Gynae",
    "MD (Physician)",
    "Pedia",
    "Ortho",
    "Dentist",
    "Cardio",
    "Diabetic",
    "Surgeon",
    "Endocrinologist",
    "Gastro",
    "E.N.T",
    "Derma",
    "Optha",
    "Pulmonologist",
    "Urologist",
    "Neuro",
  ];
  final groupedImages = [
    [
      '1.jpg',
      'Amoxsenim.jpg',
      'Crasenim.jpg',
      'Vimily.jpg',
      'Pansenim.jpg',
      'Telsenim.jpg',
      'Metsenim.jpg',
    ],
    [
      '1.jpg',
      'Telsenim.jpg',
      'Metsenim.jpg',
      'Crasenim.jpg',
      'Amoxsenim.jpg',
      'Pansenim.jpg',
      'Vimily.jpg',
    ],
    [
      '1.jpg',
      'Gyanic.jpg',
      'Vimily.jpg',
      'Amoxsenim.jpg',
      'Pansenim.jpg',
      'Telsenim.jpg',
    ],
    [
      '1.jpg',
      'Telsenim.jpg',
      'Metsenim.jpg',
      'Crasenim.jpg',
      'Amoxsenim.jpg',
      'Pansenim.jpg',
    ],
    ['1.jpg', 'Babybar.jpg'], // pedia
    ['1.jpg', 'Crasenim.jpg', 'Amoxsenim.jpg', 'Pansenim.jpg'],
    ['1.jpg', 'Amoxsenim.jpg', 'Pansenim.jpg'],
    ['1.jpg', 'Telsenim.jpg', 'Crasenim.jpg', 'Metsenim.jpg'],
    ['1.jpg', 'Metsenim.jpg', 'Crasenim.jpg', 'Telsenim.jpg'],
    ['1.jpg', 'Amoxsenim.jpg', 'Crasenim.jpg', 'Pansenim.jpg'],
    [
      '1.jpg',
      'Telsenim.jpg',
      'Metsenim.jpg',
      'Crasenim.jpg',
      'Amoxsenim.jpg',
      'Pansenim.jpg',
    ],
    ['1.jpg', 'Crasenim.jpg', 'Pansenim.jpg', 'Amoxsenim.jpg'],
    ['1.jpg', 'Amoxsenim.jpg', 'Pansenim.jpg', 'Crasenim.jpg'],
    ['1.jpg', 'Amoxsenim.jpg', 'Babybar.jpg', 'Pansenim.jpg'],
    ['1.jpg', 'Crasenim.jpg', 'Amoxsenim.jpg', 'Pansenim.jpg', 'Vimily.jpg'],
    ['1.jpg', 'Amoxsenim.jpg', 'Telsenim.jpg', 'Crasenim.jpg', 'Pansenim.jpg'],
    ['1.jpg', 'Crasenim.jpg', 'Telsenim.jpg', 'Amoxsenim.jpg', 'Pansenim.jpg'],
    ['1.jpg', 'Crasenim.jpg', 'Pansenim.jpg'],
  ];
  final totalMedicines = [
    'Telsenim.jpg',
    'Metsenim.jpg',
    'Amoxsenim.jpg',
    'Crasenim.jpg',
    'Gyanic.jpg',
    'Pansenim.jpg',
    'Babybar.jpg',
    'Vimily.jpg',
  ];
}
